version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  seaweedfs:
    image: chrislusf/seaweedfs
    restart: no
    ports:
      - "8333:8333"
      - "23646:23646"
    volumes:
      - "./data/seaweedfs/data:/data"
    environment:
      AWS_ACCESS_KEY_ID: formio-local
      AWS_SECRET_ACCESS_KEY: formio-local-secret
    command: server -s3
  api-server:
    image: formio/formio-enterprise:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048m
    links:
      - mongo
    ports:
      - "3000:3000"
    environment:
      DB_SECRET: formio-local-db-secret
      JWT_SECRET: formio-local-jwt-secret
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASS: admin
      MONGO: mongodb://mongo:27017/formio
      PDF_SERVER: ""
      PORTAL_ENABLED: 1
      PORT: 3000
    env_file:
      - data/.env
  nginx-proxy:
    image: nginx
    restart: always
    deploy:
      resources:
        limits:
          memory: 128m
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d:ro"
    links:
      - api-server

volumes:
  mongo-data:
